name: arb_translate
description:
  Command-line tool automatically adding missing message translations to ARB
  files using Google Gemini LLM.
version: 0.0.1
repository: https://github.com/leancodepl/arb_translate

executables:
  arb_translate:

environment:
  sdk: ^3.2.5

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  file: ^6.1.4
  google_generative_ai: ^0.1.0
  http: ^1.2.0
  intl: ^0.18.1
  meta: ^1.10.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
